AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: 'c4c_ticket

  Sample SAM Template for c4c_ticket

  '
Globals:
  Function:
    Timeout: 600
Resources:
  C4cTicketCollectionFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: c4c_ticket_fn
      Description: Get c4c data and load it to s3 bucket
      Role: arn:aws:iam::052471178001:role/thiruLambdaRole
      CodeUri: s3://test-kadl/297c9451fc5dac262de75284430faded
      Handler: c4c_ticket_collection.lambda_handler
      Runtime: python3.7
      Events:
        GetC4Cdata:
          Type: Api
          Properties:
            Path: /c4c
            Method: get
Outputs:
  c4cTicketApi:
    Description: API Gateway endpoint URL for Prod stage for Hello World function
    Value:
      Fn::Sub: https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/c4c/
  C4cTicketCollectionFunction:
    Description: Hello World Lambda Function ARN
    Value:
      Fn::GetAtt:
      - C4cTicketCollectionFunction
      - Arn
